version: '3.3'
services:
  myapp:
    build:
      context: .
    ports:
      - "3001:8080"

  db1:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "doctoralia"
    ports:
      - "3306:3306"
  
  db2:
    image: mongo

  adminer:
    image: adminer
    ports: 
      - "3002:8080"
    links:
      - "db1:db1"